fix: APP-6323 Update Security Alerts (#336)
* APP-6323 : Update Security Alerts

- Added a flag to enable Trivy to generate security reports too
- It will post a PR comment about the trivy scanning results too
- It will fail if any secret in found in the code

* fixed ruff related errors

* fix upload results error

this error : Uploading results
  Processing sarif files: ["trivy-secret-results.sarif"]
  Validating trivy-secret-results.sarif
  Combining SARIF files using the CodeQL CLI
  Adding fingerprints to SARIF file. See https://docs.github.com/en/enterprise-cloud@latest/code-security/code-scanning/integrating-with-code-scanning/sarif-support-for-code-scanning#providing-data-to-track-code-scanning-alerts-across-runs for more information.
  Error: Aborting upload: only one run of the codeql/analyze or codeql/upload-sarif actions is allowed per job per tool/category. The easiest fix is to specify a unique value for the `category` input. If .runs[].automationDetails.id is specified in the sarif file, that will take precedence over your configured `category`. Category: (.github/workflows/pull_request.yaml:trivy/) Tool: (Trivy) was fixed.

* added severity to trivy scan

* modified trivy-to-markdown script

Updated trivy-to-markdown script to properly parse the output.json and have different title's for secret and vulnerability scanning

* Updated trivy-to-markdown

- Modified the rule to scan all secret irrespective of the severity
- Modify trivy-to-markdown to throw correct error messages.

* Updated trivy/action.yaml

manually defining directory to scan secrets for

* Update action.yaml

Added logic to send slack alerts if secrets or vulnerabilities are detected.

* updated action.yaml

Fixed :

The template is not valid. /home/runner/work/application-sdk/application-sdk/./.github/actions/trivy/action.yaml (Line: 159, Col: 28): Unrecognized named-value: 'secrets'. Located at position 1 within expression:

issue by taking slack-webhook-url as an required input.

* Update action.yaml

Made slack-webhook-URL optional and slack notification functionality will only work when webhook-URL is passed as an input to this action.

* Removed unused imports.

Removed unused imports.

* Re-imported daft

Re-imported daft

* reimported Engine in sql_query

* removed daft and engine

* Empty commit