chore: removing push to dockerhub
token does not have permissions to push to dockerhub. Getting this error message :

#31 exporting to image
#31 pushing layers 0.4s done
#31 ERROR: failed to push registry-1.docker.io/atlanhq/application-sdk:chainguard-image-a13ffd1abcd: failed to authorize: failed to fetch oauth token: unexpected status from GET request to https://auth.docker.io/token?scope=repository%3Aatlanhq%2Fapplication-sdk%3Apull%2Cpush&service=registry.docker.io: 401 Unauthorized: access token has insufficient scopes
------
 > exporting to image:
------
ERROR: failed to build: failed to solve: failed to fetch oauth token: unexpected status from GET request to https://auth.docker.io/token?scope=repository%3Aatlanhq%2Fapplication-sdk%3Apull%2Cpush&service=registry.docker.io: 401 Unauthorized: access token has insufficient scopes
Reference
Check build summary support
Error: buildx failed with: ERROR: failed to build: failed to solve: failed to fetch oauth token: unexpected status from GET request to https://auth.docker.io/token?scope=repository%3Aatlanhq%2Fapplication-sdk%3Apull%2Cpush&service=registry.docker.io: 401 Unauthorized: access token has insufficient scopes